### ISSUE TITLE
ValueError: zero-size array to reduction operation maximum which has no identity

### ISSUE THREAD

**Issue by anushiya1** [erichson/optht#3]
Hi there,

Thank you for this really useful Python implementation of the Optimal hard threshold method.

When I run it with my input matrix (28 x28) and S (28,0) with unknown sigma, I get the following error:

ValueError: zero-size array to reduction operation maximum which has no identity

From my online search, I see the error usually happens when you pass in an empty matrix. However, I don't think I am passing in an empty matrix.

Appreciate it if you could shed some light on it.

Thank you!

**Comment by erichson** [comment]
@anushiya1 I am not sure if you have figured it out yet, but an array S that has dimension (28,0) is an empty array and hence you get an error. To illustrate this:
```
import numpy as np
S = np.ones((28,0)) 
print(S)
```
array([], shape=(28, 0), dtype=float64)

So in order to use the function, you need to supply a vector of dimension 28 that has the singular values as elements. 

Best,
Ben

**Comment by anushiya1** [comment]
> @anushiya1 I am not sure if you have figured it out yet, but an array S that has dimension (28,0) is an empty array and hence you get an error. To illustrate this:
> 
> ```
> import numpy as np
> S = np.ones((28,0)) 
> print(S)
> ```
> 
> array([], shape=(28, 0), dtype=float64)
> 
> So in order to use the function, you need to supply a vector of dimension 28 that has the singular values as elements.
> 
> Best,
> Ben

**Comment by anushiya1** [comment]
> @anushiya1 I am not sure if you have figured it out yet, but an array S that has dimension (28,0) is an empty array and hence you get an error. To illustrate this:
> 
> ```
> import numpy as np
> S = np.ones((28,0)) 
> print(S)
> ```
> 
> array([], shape=(28, 0), dtype=float64)
> 
> So in order to use the function, you need to supply a vector of dimension 28 that has the singular values as elements.
> 
> Best,
> Ben

Thank you for the explanation!
